apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kapp.k14s.io/change-group: "cm-rbac"
  name: cert-manager-postgres-install-cluster-admin-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: "cm-rbac"
  name: cert-manager-postgres-install-cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-postgres-install-cluster-admin-role
subjects:
  - kind: ServiceAccount
    name: cert-manager-postgres-install-sa
    namespace: postgres-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: "cm-rbac"
  name: cert-manager-postgres-install-sa
  namespace: postgres-install