---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: postgres-install
  annotations:
    kapp.k14s.io/change-group: "cert-manager-package"
    kapp.k14s.io/change-rule.create-order-0: "upsert after upserting tanzu-tap-repo"
    kapp.k14s.io/change-rule.create-order-1: "upsert after upserting cm-rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting cm-rbac"
    packaging.carvel.dev/downgradable: ""
spec:
  serviceAccountName: cert-manager-postgres-install-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: "2.4.1"
      prereleases: {}
  values:
    - secretRef:
        name: cert-manager-values

---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-values
  namespace: postgres-install
stringData:
  values.yaml: |
    issuers:
      - name: postgres-ingress-selfsigned
        self_signed: {}