apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pg-tap-gui
  namespace: postgres-tap-gui
  annotations:
    kapp.k14s.io/change-group: "postgres-tap-gui"
spec:
  serviceType: LoadBalancer
  readOnlyServiceType: LoadBalancer
  storageClassName: default
  storageSize: 5G
  highAvailability:
    enabled: true
    readReplicas: 1
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: registry-credentials
  pgConfig:
    dbname: tap-gui
    username: pgadmin
    appUser: pgappuser
    readOnlyUser: pgrouser
    readWriteUser: pgrwuser
  customConfig:
    pghba:
      name: pg-tap-gui-hba-configmap