apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: registry-credentials
  namespace: postgres-tap-gui
  annotations:
    kapp.k14s.io/change-group: "postgres-tap-gui"
spec:
  fromNamespace: vmware-postgres-operator