apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: postgres-install
  namespace: postgres-install
  annotations:
    kapp.k14s.io/change-group: "postgres-install-app"
    kapp.k14s.io/disable-wait: ""
    kapp.k14s.io/change-rule.create-order-0: "upsert after upserting cert-manager-package"
    kapp.k14s.io/change-rule.delete-order-0: "delete before deleting cert-manager-package"
spec:
  serviceAccountName: postgres-installer-sa
  fetch:
    - git:
        url: https://gitlab.company.com/my-group/platform-automation
        ref: origin/main
        subPath: clusters/postgres/install
        secretRef:
          name: postgres-install-creds
  template:
    - ytt: { }

  deploy:
    - kapp:
        rawOptions:
          - --diff-changes=true