apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: registry-credentials
  namespace: postgres-metadata-store
  annotations:
    kapp.k14s.io/change-group: "postgres-metadata-store"
spec:
  fromNamespace: postgres-install