apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kapp.k14s.io/change-group: "postgres-operator-package"
    kapp.k14s.io/change-rule.create-order-1: "upsert after upserting postgres-operator"
    kapp.k14s.io/change-rule.create-order-3: "delete before deleting postgres-operator"
  name: tanzu-tds-repository
  namespace: vmware-postgres-operator
spec:
  fetch:
    imgpkgBundle:
      image: harbor.example.com/tanzu-data-services/tds-packages:1.12.0
      secretRef: 
        name: registry-credentials