apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: postgres-install
  annotations:
    kapp.k14s.io/change-group: "tanzu-tap-repo"
    kapp.k14s.io/change-rule.delete-order: "delete after deleting cert-manager-package"
spec:
  toNamespaces:
    - '*'